[shell]
program = "/home/gennadi/.nix-profile/bin/fish"

[font]
size = 14

[font.glyph_offset]
y = 4

[font.offset]
y = 8

[font.bold]
family = "Monaspace Krypton"
style = "bold"

[font.italic]
family = "Monaspace Radon Var"
style = "Italic"

[font.normal]
family = "Monaspace Neon"
style = "Regular"

[window]
resize_increments = true

[window.padding]
x = 10
y = 10

[colors.primary]
background = "#fafafa"
foreground = "#6a6a6a"

[colors.normal]
black = "#6a6a6a"
blue = "#118dc3"
cyan = "#56b6c2"
green = "#1da912"
magenta = "#9a77cf"
red = "#e05661"
white = "#fafafa"
yellow = "#eea825"

[colors.bright]
black = "#848484"
blue = "#1caceb"
cyan = "#7bc6d0"
green = "#25d717"
magenta = "#b69ddc"
red = "#e88189"
white = "#ffffff"
yellow = "#f2bb54"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.selection]
background = "#bebebe"
text = "CellForeground"

