import:
  - ~/.config/alacritty/github_light.yml
window:
  position:
    x: 10
    y: 10

  padding:
    x: 10
    y: 10
#env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  #TERM: alacritty

  #class:
    # Application instance name
    #instance: Alacritty
    # General application class
    #general: Alacritty

  # Decorations theme variant
  #
  # Override the variant of the System theme/GTK theme/Wayland client side
  # decorations. Commonly supported values are `Dark`, `Light`, and `None` for
  # auto pick-up. Set this to `None` to use the default theme variant.
  #decorations_theme_variant: None

  # Resize increments
  #
  # Prefer resizing window by discrete steps equal to cell dimensions.
  #resize_increments: false

  # Make `Option` key behave as `Alt` (macOS only):
  #   - OnlyLeft
  #   - OnlyRight
  #   - Both
  #   - None (default)
  #option_as_alt: None

#scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  #history: 10000

  # Scrolling distance multiplier.
  #multiplier: 3

# Font configuration
font:
  normal:
    family: VictorMono Nerd Font
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: VictorMono Nerd Font

    # The `style` can be specified to pick a specific face.
    #style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: VictorMono Nerd Font

    # The `style` can be specified to pick a specific face.
    #style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: VictorMono Nerd Font

    # The `style` can be specified to pick a specific face.
    #style: Bold Italic

  # Point size
  size: 14.0

  # Offset is the extra space around each character. `offset.y` can be thought
  # of as modifying the line spacing, and `offset.x` as modifying the letter
  # spacing.
  offset:
    #  x: 0
    y: 14

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the
  # right, increasing `y` moves the glyph upward.
  glyph_offset:
    #  x: 0
    y: 7

# github Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0xffffff'
    foreground: '0x24292f'

  # Normal colors
  normal:
    black:   '0x24292e'
    red:     '0xd73a49'
    green:   '0x28a745'
    yellow:  '0xdbab09'
    blue:    '0x0366d6'
    magenta: '0x5a32a3'
    cyan:    '0x0598bc'
    white:   '0x6a737d'

  # Bright colors
  bright:
    black:   '0x959da5'
    red:     '0xcb2431'
    green:   '0x22863a'
    yellow:  '0xb08800'
    blue:    '0x005cc5'
    magenta: '0x5a32a3'
    cyan:    '0x3192aa'
    white:   '0xd1d5da'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xcb2431' }
