import:
 - ~/.config/alacritty/colors.yml
 - ~/.config/alacritty/key_bindings.yml

env:
  DARK_MODE: 'false'
window:
  decorations: none
  dimensions:
    columns: 156
    lines: 28
  padding:
    x: 0
    y: 0
  dynamic_padding: true
  title: a
  dynamic_title: true
font:
  normal:
    family: 'JetBrainsMono Nerd Font'
    style: Regular
  bold:
    family: 'JetBrainsMono Nerd Font'
    style: Bold
  italic:
    family: 'JetBrainsMono Nerd Font'
    style: Italic
  size: 14
  offset:
    x: 0
    y: 24

  glyph_offset:
    x: 0
    y: 12
