import:
 - ~/.config/alacritty/colors.yml
 - ~/.config/alacritty/key_bindings.yml

env:
  DARK_MODE: 'false'
window:
  # decorations: buttonless
  dimensions:
    columns: 156
    lines: 28
  padding:
    x: 4
    y: 2
  dynamic_padding: true
  title: a
  dynamic_title: true

  # background_opacity: 0.5
font:
  use_thin_strokes: true
  normal:
    family: 'JetBrainsMono Nerd Font'
    style: Regular
  bold:
    family: 'JetBrainsMono Nerd Font'
    style: Bold
  italic:
    family: 'JetBrainsMono Nerd Font'
    style: Italic
  size: 14
  offset:
    x: 0
    y: 16

  glyph_offset:
    x: 0
    y: 10
