schemes:
# github Alacritty Colors
  github: &github
    # Default colors
    primary:
      background: '0xffffff'
      foreground: '0x0E1116'

    # Normal colors
    normal:
      black:   '0x24292f'
      red:     '0xcf222e'
      green:   '0x116329'
      yellow:  '0x4d2d00'
      blue:    '0x0969da'
      magenta: '0x8250df'
      cyan:    '0x1b7c83'
      white:   '0x6e7781'

    # Bright colors
    bright:
      black:   '0x57606a'
      red:     '0xa40e26'
      green:   '0x1a7f37'
      yellow:  '0x633c01'
      blue:    '0x218bff'
      magenta: '0xa475f9'
      cyan:    '0x3192aa'
      white:   '0x8c959f'

    indexed_colors:
      - { index: 16, color: '0xd18616' }
      - { index: 17, color: '0xa40e26' }

  edge_light: &edge_light
    primary:
      background: "0xfafafa"
      foreground: "0x4b505b"

    normal:
      black: "0x4b505b"
      red: "0xd05858"
      green: "0x608e32"
      yellow: "0xbe7e05"
      blue: "0x5079be"
      magenta: "0xb05ccc"
      cyan: "0x3a8b84"
      white: "0xfafafa"

    bright:
      black: "0x4b505b"
      red: "0xd05858"
      green: "0x608e32"
      yellow: "0xbe7e05"
      blue: "0x5079be"
      magenta: "0xb05ccc"
      cyan: "0x3a8b84"
      white: "0xfafafa"



  edge_dark_neon:  &edge_dark
    primary:
      background: "0x2b2d3a"
      foreground: "0xc5cdd9"

    normal:
      black: "0x363a4e"
      red: "0xec7279"
      green: "0xa0c980"
      yellow: "0xdeb974"
      blue: "0x6cb6eb"
      magenta: "0xd38aea"
      cyan: "0x5dbbc1"
      white: "0xc5cdd9"

    bright:
      black: "0x363a4e"
      red: "0xec7279"
      green: "0xa0c980"
      yellow: "0xdeb974"
      blue: "0x6cb6eb"
      magenta: "0xd38aea"
      cyan: "0x5dbbc1"
      white: "0xc5cdd9"

# colors: *light_dark
colors: *github

