require("config.options")
require("config.keymaps")
require("config.lsps")

require('plugins.theme')
require('plugins.treesitter')
require('plugins.lualine')
require('plugins.mini')
require('plugins.blink')
require('plugins.lazydev')
require('plugins.gitsigns')
