-- require("onenord").setup {
--     borders = true, -- Split window borders
--     italics = {
--         comments = true, -- Italic comments
--         strings = false, -- Italic strings
--         keywords = false, -- Italic keywords
--         functions = false, -- Italic functions
--         variables = false, -- Italic variables
--     },
--     disable = {
--         background = false, -- Disable setting the background color
--         cursorline = false, -- Disable the cursorline
--         eob_lines = true, -- Hide the end-of-buffer lines
--     },
--     custom_highlights = {}, -- Overwrite default highlight groups
-- }

-- require("github-theme").setup {
--     -- theme_style = "light",
--     comment_style = "italic",
--     function_style = "bolditalic",
--     keyword_style = "bold",
--     transparent = false,
--     dark_sidebar = false,
--     colors = { hint = "orange", error = "#ff0000" },
--     overrides = function(c)
--         return {
--             -- CursorLine = { bg = "#FFFBDD" },
--         }
--     end,
-- }

vim.cmd [[ colorscheme sonokai]]
