return {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
        {
            "gbprod/php-enhanced-treesitter.nvim",
            enabled = false,
            ft = { "php" },
        },
    },
    opts = {
        highlight = { enable = true },
        indent = { enable = true },
        ensure_installed = {
            "bash",
            "c",
            "diff",
            "html",
            "javascript",
            "jsdoc",
            "json",
            "jsonc",
            "lua",
            "luadoc",
            "luap",
            "markdown",
            "markdown_inline",
            "printf",
            "python",
            "query",
            "regex",
            "make",
            "toml",
            "twig",
            "tsx",
            "typescript",
            "vim",
            "vimdoc",
            "xml",
            "yaml",
        },
    },
}
