return {
    "nvim-treesitter/nvim-treesitter",
    event = "VeryLazy",
    dependencies = {
        "nvim-treesitter/playground",
        "gbprod/php-enhanced-treesitter.nvim",
    },
    config = function()
        require("nvim-treesitter.configs").setup({
            ensure_installed = {
                "bash",
                "c",
                "clojure",
                "css",
                "dockerfile",
                "fish",
                "gitcommit",
                "gitignore",
                "go",
                "html",
                "ini",
                "json",
                "lua",
                "make",
                "markdown",
                "markdown_inline",
                "nix",
                "php",
                "regex",
                "scheme",
                "sql",
                "toml",
                "twig",
                "vim",
                "vimdoc",
                "yaml",
                -- "phpdoc",
            },
            highlight = { enable = true },
            indent = { enable = true },
        })
    end,
}
