git:
  paging:
    useConfig: false
    pager: delta --paging=never --syntax-theme="GitHub"
  branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=oneline {{branchName}} --'
  allBranchesLogCmd: 'git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=short'
